/**
 * Table schemas — Zod schemas for all Supabase public tables, views, enums and functions.
 *
 * Generated by supazod from lib/types/database.ts. Do not edit generated.ts by hand.
 *
 * Regenerate after schema changes:
 *   npm run schema:generate
 *
 * (Ensure lib/types/database.ts is up to date first, e.g. via Supabase MCP
 *  generate_typescript_types or: npx supabase gen types typescript --project-id <id>)
 */
export * from "./generated"
