import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner"
import { AuthProvider } from "@/contexts/auth-context"
import { getAuthSession } from "@/lib/auth/session"
import { fetchUserProfile } from "@/lib/auth/user-profile"
import { createSupabaseServerClient } from "@/lib/supabase/server"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServerClient()
  const { user, role } = await getAuthSession(supabase)
  const profile = user ? await fetchUserProfile(supabase, user) : null

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className="antialiased"
      >
        <AuthProvider
          initialUser={user}
          initialRole={role}
          initialProfile={profile}
        >
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
