/**
 * Central types for Flight Desk — database schema, roles, and helpers.
 * Use these in API routes, server components, and client code for type-safe DB access.
 */

import type { Database } from "./database"

// Re-export full Supabase schema (tables, enums, functions)
export type { Database, Json } from "./database"

// App role types (RBAC)
export type { UserRole } from "./roles"
export { ROLE_HIERARCHY, isRoleAtLeast } from "./roles"

// Convenience: public schema tables — use Tables<"aircraft"> for Row, TablesInsert<"aircraft"> for Insert, etc.
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"]
export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"]

// Public enums (for type-safe enum usage)
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T]

// Named table types (Row, Insert, Update per table) — e.g. BookingRow, AircraftInsert
export type {
  AircraftRow,
  AircraftInsert,
  AircraftUpdate,
  AircraftChargeRatesRow,
  AircraftChargeRatesInsert,
  AircraftChargeRatesUpdate,
  AircraftComponentsRow,
  AircraftComponentsInsert,
  AircraftComponentsUpdate,
  AircraftTypesRow,
  AircraftTypesInsert,
  AircraftTypesUpdate,
  AuditLogsRow,
  AuditLogsInsert,
  AuditLogsUpdate,
  BookingRow,
  BookingInsert,
  BookingUpdate,
  CancellationCategoriesRow,
  CancellationCategoriesInsert,
  CancellationCategoriesUpdate,
  ChargeableTypesRow,
  ChargeableTypesInsert,
  ChargeableTypesUpdate,
  ChargeablesRow,
  ChargeablesInsert,
  ChargeablesUpdate,
  EmailLogsRow,
  EmailLogsInsert,
  EmailLogsUpdate,
  EndorsementsRow,
  EndorsementsInsert,
  EndorsementsUpdate,
  EquipmentRow,
  EquipmentInsert,
  EquipmentUpdate,
  EquipmentIssuanceRow,
  EquipmentIssuanceInsert,
  EquipmentIssuanceUpdate,
  EquipmentUpdatesRow,
  EquipmentUpdatesInsert,
  EquipmentUpdatesUpdate,
  ExamRow,
  ExamInsert,
  ExamUpdate,
  ExamResultsRow,
  ExamResultsInsert,
  ExamResultsUpdate,
  ExperienceTypesRow,
  ExperienceTypesInsert,
  ExperienceTypesUpdate,
  FlightExperienceRow,
  FlightExperienceInsert,
  FlightExperienceUpdate,
  FlightTypesRow,
  FlightTypesInsert,
  FlightTypesUpdate,
  InstructorCategoriesRow,
  InstructorCategoriesInsert,
  InstructorCategoriesUpdate,
  InstructorFlightTypeRatesRow,
  InstructorFlightTypeRatesInsert,
  InstructorFlightTypeRatesUpdate,
  InstructorRow,
  InstructorInsert,
  InstructorUpdate,
  InvoiceItemsRow,
  InvoiceItemsInsert,
  InvoiceItemsUpdate,
  InvoicePaymentsRow,
  InvoicePaymentsInsert,
  InvoicePaymentsUpdate,
  InvoiceSequencesRow,
  InvoiceSequencesInsert,
  InvoiceSequencesUpdate,
  InvoiceRow,
  InvoiceInsert,
  InvoiceUpdate,
  LandingFeeRatesRow,
  LandingFeeRatesInsert,
  LandingFeeRatesUpdate,
  LessonProgressRow,
  LessonProgressInsert,
  LessonProgressUpdate,
  LessonRow,
  LessonInsert,
  LessonUpdate,
  LicensesRow,
  LicensesInsert,
  LicensesUpdate,
  MaintenanceVisitsRow,
  MaintenanceVisitsInsert,
  MaintenanceVisitsUpdate,
  MembershipTypesRow,
  MembershipTypesInsert,
  MembershipTypesUpdate,
  MembershipRow,
  MembershipInsert,
  MembershipUpdate,
  ObservationRow,
  ObservationInsert,
  ObservationUpdate,
  RoleRow,
  RoleInsert,
  RoleUpdate,
  RosterRuleRow,
  RosterRuleInsert,
  RosterRuleUpdate,
  ShiftOverrideRow,
  ShiftOverrideInsert,
  ShiftOverrideUpdate,
  StudentSyllabusEnrollmentRow,
  StudentSyllabusEnrollmentInsert,
  StudentSyllabusEnrollmentUpdate,
  SyllabusRow,
  SyllabusInsert,
  SyllabusUpdate,
  TaxRatesRow,
  TaxRatesInsert,
  TaxRatesUpdate,
  TenantSettingsRow,
  TenantSettingsInsert,
  TenantSettingsUpdate,
  TenantUserRow,
  TenantUserInsert,
  TenantUserUpdate,
  TenantRow,
  TenantInsert,
  TenantUpdate,
  TransactionRow,
  TransactionInsert,
  TransactionUpdate,
  UserPermissionOverridesRow,
  UserPermissionOverridesInsert,
  UserPermissionOverridesUpdate,
  UserRow,
  UserInsert,
  UserUpdate,
  UsersEndorsementsRow,
  UsersEndorsementsInsert,
  UsersEndorsementsUpdate,
  UserDirectoryRow,
} from "./tables"
