begin;

create table if not exists public.tenant_settings_audit (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  changed_by uuid null references auth.users(id),
  previous_settings jsonb not null default '{}'::jsonb,
  new_settings jsonb not null default '{}'::jsonb,
  changed_at timestamptz not null default now()
);

create index if not exists idx_tenant_settings_audit_tenant_changed_at
  on public.tenant_settings_audit (tenant_id, changed_at desc);

alter table public.tenant_settings_audit enable row level security;

drop policy if exists tenant_settings_audit_select on public.tenant_settings_audit;
create policy tenant_settings_audit_select
on public.tenant_settings_audit
for select
to public
using (
  public.tenant_user_has_role(
    auth.uid(),
    tenant_id,
    array['owner'::public.user_role, 'admin'::public.user_role]
  )
);

commit;
